"use strict";
let car = "Corolla";
console.log(car === "Corolla");
console.log(car === "City");
let Fruit = "Apple";
console.log(Fruit === "Banana");
console.log(Fruit === "Apple");
let number = 35;
console.log(number === 35);
console.log(number === "35");
let bike = "Honda";
console.log(bike === "Yamaha");
console.log(bike === "Honda");
let percentage = 85;
console.log(percentage === 87);
console.log(percentage === 88);
